--------------------------------------------------
version: "3.9"

services:
  server:
    build:
      context: ./server
    environment:
      - PORT=4000
      - FMP_API_KEY=${FMP_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash}
      - NODE_ENV=production
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  client:
    build:
      context: ./client
      args:
        - VITE_BACKEND_URL=http://localhost:4000
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_healthy


